config/routes.rb
Blog::Application.routes.draw do
  root :to=> "serviceexecution/startup#index"

  match 'index' => 'serviceexecution/startup#index'
  match 'registration' => 'serviceexecution/registration', :as => :registration
  match 'auth_complete/:format' => 'serviceexecution/account#showuser', :as => :auth_complete

  namespace :uploader do
    resources :pictures do
      member do
        match :upload, :via=>[:get, :post]
        match :ischecked, :via=>[:get, :post]
        match :destroy_by_name, :via=>[:get, :post]
      end
    end
  end

  namespace :serviceexecution do
    match 'web_giude' => 'menu#web_guide', :as => :web
    match 'android_giude' => 'menu#android_guide', :as => :android
    match 'fordevelopers' => 'menu#fordevelopers'
    match 'encrypt' => 'menu#encrypt'
    match 'author' => 'menu#author'
    resources :startup
    resources :account do
      member do
        match :request_file_size, :via=>[:get, :post]
        match :download, :via=>[:get, :post]
        match :showuser, :via=>[:get, :post]
        match :showprogress, :via=>[:get, :post]
      end
    end
  end

  resources :posts do
    match :showfirst, :via=>[:get, :post], :on=>:member
  end
  resources :users
  resources :user_sessions do
    member do
      match :logout, :via=>[:get, :post]
      match :create_android, :via=>[:get, :post]
    end
  end

end

app/views/widgets/footer.html.erb
    <div id="Footer">
        <img class="head_foot" src="/assets/widgets/footer.jpg" >
    </div>

app/views/widgets/header.html.erb
    <div id="Header">
      <img class="head_foot" src="/assets/widgets/header.jpg" >
      <div id="left_block">
        <div id="left_logo"></div>
        <div id="text_emblem"></div>
      </div>
      <div id="reg_auth_errors">
        <% if @user_session %>
          <% if @user_session.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@user_session.errors.count, "error") %> :</h2>

                  <ul>
                    <% @user_session.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
          <% end %>
        <% end %>

      </div>
      <div id="right_block">
        <div id="android_logo">
          <img src="/assets/widgets/android-logo-white.png" alt="Завантажити ANDROID-версію">
        </div>
        <div id="register_or_enter">
          <% @current = current_user %>
          <% if @current %>
              <div><h3>Good day, </h3><%= @current.login %></div>
              <%= link_to "Редагувати", edit_user_path(@current) %>
              <%= link_to "Вийти", logout_user_session_path(current_user_session)%>
              <%= link_to "Мої файли", showuser_serviceexecution_account_path(@current)%>
          <% else %>
              <p><a id="hover_register" href="/users/new">Зареєструватися</a> | <a id="hover_enter" href="">Увійти</a></p>

              <div id="enter_form" class="">
                <div class="image_close">
                </div>
                    <%= form_for(UserSession.new) do |f| %>
                            <%= f.label :Login %>
                            <%= f.text_field :login %>
                            <%= f.label :password %>
                            <%= f.password_field :password %>

                            <%= f.submit "Login", :class => "submit"%>
                       <% end %>
              </div>
          <% end %>
        </div>
      </div>
      <div id="container_menu">
          <div class="container">
            <div class="menu">
                <ul>
                    <li class=""><a href="/serviceexecution/startup#index" >Головна</a></li>
                    <li class=""><a href="../menu/embed.html" >Навігатор</a>
                        <ul>
                            <li class=""><a href="">Android клієнт</a></li>
                            <li class=""><a href="<%= serviceexecution_android_path %>">Довідник Android</a></li>
                            <li class=""><a href="<%= serviceexecution_web_path %>">Довідник</a></li>
                        </ul>
                    </li>

                    <li class=""><a href="../menu/zero_dollars.html" >Додаток</a>
                      <ul>
                        <li class=""><a href="<%= serviceexecution_author_path %>">Автор</a></li>
                        <li class=""><a href="<%= serviceexecution_encrypt_path %>">Шифрування</a></li>
                        <li class=""><a href="<%= serviceexecution_fordevelopers_path %>">Для розробників</a></li>
                      </ul>
                    </li>
                </ul>
            </div>
          </div>
      </div>
    </div>