config/routes.rb
Blog::Application.routes.draw do
  root :to=> "serviceexecution/startup#index"

  match 'index' => 'serviceexecution/startup#index'
  match 'registration' => 'serviceexecution/registration', :as => :registration
  match 'auth_complete/:format' => 'serviceexecution/account#showuser', :as => :auth_complete

  namespace :uploader do
    resources :pictures do
      member do
        match :upload, :via=>[:get, :post]
        match :ischecked, :via=>[:get, :post]
        match :destroy_by_name, :via=>[:get, :post]
      end
    end
  end

  namespace :serviceexecution do
    match 'web_giude' => 'menu#web_guide', :as => :web
    match 'android_giude' => 'menu#android_guide', :as => :android
    match 'fordevelopers' => 'menu#fordevelopers'
    match 'encrypt' => 'menu#encrypt'
    match 'author' => 'menu#author'
    resources :startup
    resources :account do
      member do
        match :request_file_size, :via=>[:get, :post]
        match :download, :via=>[:get, :post]
        match :showuser, :via=>[:get, :post]
        match :showprogress, :via=>[:get, :post]
      end
    end
  end

  resources :posts do
    match :showfirst, :via=>[:get, :post], :on=>:member
  end
  resources :users
  resources :user_sessions do
    member do
      match :logout, :via=>[:get, :post]
      match :create_android, :via=>[:get, :post]
    end
  end

end

app/controllers/serviceexecution/account_controller.rb
class Serviceexecution::AccountController < ApplicationController

  def showuser
    files_paths = Array.new
    if current_user != nil
      user_id = current_user.id
    else
      user_id = params[:id]
    end
    files_paths.push(user_id)
    files = Picture.find_all_by_user_id(user_id)
    files.each do |file|
        files_paths.push(file.file.model[:file])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => files_paths }
    end
  end

  def check_dec_dir(folder)
    if !File.exists?(folder)
      Dir.mkdir(folder)
    end
  end

  def request_file_size
    if (current_user) != nil
      user_id = current_user.id
    else
      user_id = params[:id]
    end
    base_url = "public/FILES/#{user_id}/"

    file = Picture.find_by_file(params[:path])
    send_file base_url+params[:path], :type => "application", :x_sendfile => true
  end

  def download
    require "crypto/encript"

    if (current_user) != nil
      user_id = current_user.id
    else
      user_id = params[:id]
    end
    base_url = "public/FILES/#{user_id}/"
    dec_url = "public/FILES/#{user_id}/tmp/"

    check_dec_dir(dec_url)

    file = Picture.find_by_file(params[:path])

    if file.key != "0"
      crypt = Crypto::Encrypt.new
      enc = File.open(base_url+params[:path], "r+b")
      size = File.size(enc)
      dec = File.open(dec_url+params[:path], "wb")

      file_length = 0
      no_data = false

      while file_length != size
        word = Array.new
        coded_flags = Array.new
        slots=1
        while ((no_data!=true) && (slots!=(crypt.thread_count+1)))
          ost = size - file_length
          if ost<8
            coded_flags[slots-1] = 0
            no_data = true
            word[slots-1] = Array.new
            for i in 1..ost
              word[slots-1][i-1] = enc.getc
            end
            file_length += word[slots-1].size
            slots+=1
          else
            coded_flags[slots-1] = 1
            word[slots-1] = Array.new
            for i in 1..8
              word[slots-1][i-1] = enc.getc
            end
            file_length += word[slots-1].size
            slots+=1
          end
        end

        threads = Array.new
        for slots in 1..word.size
          if (word[slots-1].size == 8)
            threads[slots-1] = Thread.new{
              word[slots-1] = crypt.descrypt(94, crypt.text_8_to_32_mas(word[slots-1]))
            }.join
          end
        end

        for slots in 1..word.size
          if (coded_flags[slots-1]==0)
            for i in 1..word[slots-1].size
              dec.putc(word[slots-1][i-1])
            end
          else
            descrypt = crypt.text_32_to_8_string(word[slots-1])
            for i in 1..8
              dec.putc(descrypt[i-1])
            end
          end
        end

      end

      enc.close
      dec.close

      send_file dec_url+params[:path], :type => "application", :x_sendfile => true

    else
      send_file base_url+params[:path], :type => "application", :x_sendfile => true
    end

  end


end

app/controllers/serviceexecution/menu_controller.rb
class Serviceexecution::MenuController < ApplicationController

    def android_guide
      respond_to do |format|
        format.html
      end
    end

    def web_guide
      respond_to do |format|
        format.html
      end
    end

    def fordevelopers
      respond_to do |format|
        format.html
      end
    end



    def encrypt
      respond_to do |format|
        format.html
      end
    end

    def author
      respond_to do |format|
        format.html
      end
    end
end

app/controllers/serviceexecution/regsitration_controller.rb
class Serviceexecution::RegsitrationController < ApplicationController
  def index
    respond_to do |format|
      format.html
    end
  end

end

app/controllers/serviceexecution/startup_controller.rb
class Serviceexecution::StartupController < ApplicationController
  def index

    unless current_user
      @user = User.new
      @user_session = UserSession.new
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end
end

app/helpers/serviceexecution/regsitration_helper.rb
module Serviceexecution::RegsitrationHelper
end

app/helpers/serviceexecution/startup_helper.rb
module Serviceexecution::StartupHelper
end

app/views/serviceexecution/account/showuser.html.erb
    <%= render :template => 'widgets/header'  %>

    <div id="dialog" title="Видалення файлу" style="display: none;">
      <p>Увага! Після видалення файл/файли буде неможливо відновити.</p>
      <p>Ви дійсно хочете здійснити операцію видалення?</p>
    </div>

    <div id="Content_parent">
        <table id="Content_parent_table">
          <tr>
            <td id="SidebarL"></td>
            <td id="Content"  class="">
              <div id="header_catalog" >
                <p>Файли каталогу</p>
                <div id="upload_image">
                    <img src="/assets/serviceexecution/Upload.png" width="56">
                </div>
              </div>
              <div id="encrypt_warning">
                <p>Шифрування увімкнено</p>
              </div>
              <div class="files_container">
                <%= form_for [:uploader, Picture.new], :html => { :multipart => true, :id => "fileupload"  } do |f| %>
                  <div class="row fileupload-buttonbar no_margin">
                            <div class="span7 centrino">
                                <span class="btn btn-success fileinput-button">
                                    <i class="icon-plus icon-white"></i>
                                    <span>Add files...</span>
                                    <%= f.file_field :file %>
                                </span>
                                <button type="submit" class="btn btn-primary start">
                                    <i class="icon-upload icon-white"></i>
                                    <span>Start upload</span>
                                </button>
                                <button type="reset" class="btn btn-warning cancel">
                                    <i class="icon-ban-circle icon-white"></i>
                                    <span>Cancel upload</span>
                                </button>
                                <button type="button" class="btn btn-danger delete">
                                    <i class="icon-trash icon-white"></i>
                                    <span>Delete</span>
                                </button>
                                <input type="checkbox" class="toggle">
                            </div>
                            <div>
                                <!-- The global progress bar -->
                                <div class="progress progress-success progress-striped active fade">
                                    <div class="bar" style="width:0%;"></div>
                                </div>
                            </div>
                        </div>
                        <!-- The loading indicator is shown during image processing -->
                        <div class="fileupload-loading"></div>
                        <div id="encrypt_enabled">
                          <input class="enabler" type="checkbox" onclick="Encryption()"/>
                          <b>Увімкнути шифрування</b>
                        </div>
                        <br>

                        <!-- The table listing the files available for upload/download -->
                        <table id="table_of_files" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
                <% end %>
              </div>
            </td>
            <td id="SidebarR"></td>
          </tr>
        </table>
    </div>

                <script>
              var fileUploadErrors = {
                maxFileSize: 'File is too big',
                minFileSize: 'File is too small',
                acceptFileTypes: 'Filetype not allowed',
                maxNumberOfFiles: 'Max number of files exceeded',
                uploadedBytes: 'Uploaded bytes exceed file size',
                emptyResult: 'Empty file upload result'
              };
            </script>

            <!-- The template to display files available for download -->
            <script id="template-download" type="text/x-tmpl">
            {% for (var i=0, file; file=o.files[i]; i++) { %}

                <tr class="template-download fade">
                    {% if (file.error) { %}
                        <td></td>
                        <td class="name"><span>{%=file.file%}</span></td>
                        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
                        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
                    {% } else { %}
                        <td class="preview">{% if (file.thumbnail_url) { %}
                            <a href="<%= download_serviceexecution_account_path(:id=>current_user.id)%>?path={%=file.file%}" title="{%=file.file%}" download="{%=file.name%}" onclick="Download(this)"><img style="width : 50px; height : 50px;" src="{%=file.thumbnail_url%}"></a>
                        {% } %}</td>
                        <td class="name">
                            <a href="<%= download_serviceexecution_account_path(:id=>current_user.id)%>?path={%=file.file%}" title="{%=file.file%}" download="{%=file.name%}" onclick="Download(this)">{%=file.file%}</a>
                        </td>
                        <td class="size" style="text-align: center;"><span>{%=o.formatFileSize(file.size)%}</span></td>
                        <td colspan="2" style="width: 20%;"><div class="downloading_div" style="display:none; width: 100%;"><span>Зачекайте будь-ласка...</span></div></td>
                    {% } %}
                    <td class="delete">
                        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                            <i class="icon-trash icon-white"></i>
                            <span>{%=locale.fileupload.destroy%}</span>
                        </button>
                        <input type="checkbox" name="delete" value="1">
                    </td>
                </tr>
            {% } %}
            </script>

            <script id="template-upload" type="text/x-tmpl">
            {% for (var i=0, file; file=o.files[i]; i++) { %}
                <tr class="template-upload fade">
                    <td class="preview"><span class="fade"></span></td>
                    <td class="name"><span>{%=file.name%}</span></td>
                    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
                    {% if (file.error) { %}
                        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
                    {% } else if (o.files.valid && !i) { %}
                        <td>
                            <div class="progress progress-success progress-striped active" style="height: auto;"><div class="bar" style="width:0%;"></div><div class="loading_div"><a>Завантаження</a><a></a></div></div>
                        </td>
                        <td class="start">{% if (!o.options.autoUpload) { %}
                            <button class="btn btn-primary">
                                <i class="icon-upload icon-white"></i>
                                <span>{%=locale.fileupload.start%}</span>
                            </button>
                        {% } %}</td>
                    {% } else { %}
                        <td colspan="2"></td>
                    {% } %}
                    <td class="cancel">{% if (!i) { %}
                        <button class="btn btn-warning">
                            <i class="icon-ban-circle icon-white"></i>
                            <span>{%=locale.fileupload.cancel%}</span>
                        </button>
                    {% } %}</td>
                </tr>
            {% } %}
            </script>

    <%= render :template => 'widgets/footer'  %>

app/views/serviceexecution/account/upload.js.erb
$(function() {
    $('#user_files').append('<%= (params[:Filedata].original_filename) %>');
    alert('added');
});