config/routes.rb
Blog::Application.routes.draw do
  root :to=> "serviceexecution/startup#index"

  match 'index' => 'serviceexecution/startup#index'
  match 'registration' => 'serviceexecution/registration', :as => :registration
  match 'auth_complete/:format' => 'serviceexecution/account#showuser', :as => :auth_complete

  namespace :uploader do
    resources :pictures do
      member do
        match :upload, :via=>[:get, :post]
        match :ischecked, :via=>[:get, :post]
        match :destroy_by_name, :via=>[:get, :post]
      end
    end
  end

  namespace :serviceexecution do
    match 'web_giude' => 'menu#web_guide', :as => :web
    match 'android_giude' => 'menu#android_guide', :as => :android
    match 'fordevelopers' => 'menu#fordevelopers'
    match 'encrypt' => 'menu#encrypt'
    match 'author' => 'menu#author'
    resources :startup
    resources :account do
      member do
        match :request_file_size, :via=>[:get, :post]
        match :download, :via=>[:get, :post]
        match :showuser, :via=>[:get, :post]
        match :showprogress, :via=>[:get, :post]
      end
    end
  end

  resources :posts do
    match :showfirst, :via=>[:get, :post], :on=>:member
  end
  resources :users
  resources :user_sessions do
    member do
      match :logout, :via=>[:get, :post]
      match :create_android, :via=>[:get, :post]
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index

    @user = User.new
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, :notice => 'Post was successfully created.' }
        format.json { render :json => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, :notice => 'Post was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :ok }
    end
  end
  def showfirst
    #@post = Post.find(1)
    @user ||= User.find_by_login(params[:user][:login])
    @email = params[:user][:email]
    if @user != NIL
    if @user.email == @email
      flash[:notice] = "Welcome, #{@user.login}!"
      redirect_to :action => :index
    end
    else
      flash[:error] = "Login invalid."
      redirect_to :action => :index
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div> 
<h2><%= link_to post.title, :action => 'show', :id => post %></h2> 
<p><%= post.body %></p> 
<p><small> <%= post.created_at.to_s %> 
</small></p> 
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if flash[:error] %>
    <div>
      <%= flash[:error] %>
    </div>
<% end %>
<% if flash.notice %>
    <div>
      <%= flash.notice %>
    </div>
<% end %>
<%= form_for(:user, :url=>showfirst_post_path(:user)) do |field| %>
    <div>
      <%= field.label :Login %>
      <%= field.text_field :login %>
    </div>
    <div>
      <%= field.label :Password %>
      <%= field.text_field :email %>
    </div>
    <div>
        <%= field.submit "Log in"%>
    </div>
<% end %>
<%= link_to 'Show first', showfirst_post_path(@posts[1])%>
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Created at</th>
    <th></th>
    <th></th>
  </tr>
    <th></th>

<% @posts.each do |post| %>
  <tr>
    <td><%= link_to 'Show first', showfirst_post_path(post)%></td>
    <td><%= post.title %></td>
    <td><%= post.body %></td>
    <td><%= post.created_at %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>

<p>
  <b>Created at:</b>
  <%= @post.created_at %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/showfirst.html.erb
<%= @post.title%>